# Generated by Django 4.2.7 on 2023-11-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_push', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linear_velocity', models.FloatField()),
                ('angular_velocity', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Robot',
        ),
    ]
